
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const SURVEYMATTER = 'SURVEYMATTER';
export const UPDATE_ALLOWED_USER = 'UPDATE_ALLOWED_USER';
export const UPDATE_ANSWER = 'UPDATE_ANSWER';
export const ADD_ANSWER = 'ADD_ANSWER';
export const DURATION = 'DURATION';
export const DELETE_SURVEY_DATA = 'DELETE_SURVEY_DATA';


